# 修改端口
server:
  port: 8081
# 配置rabbitmq
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # publisher-confirms: true	# 开启confirms模式
    publisher-returns: true 	# 开启returncallback模式